<?php

namespace WPGraphQL\Cognito_Authentication;

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class AWSCognitoGraphQL {
	private $aws_cognito_graphql_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'aws_cognito_graphql_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'aws_cognito_graphql_page_init' ) );
	}

	public function aws_cognito_graphql_add_plugin_page() {
		add_menu_page(
			'AWS Cognito GraphQL', // page_title
			'AWS Cognito GraphQL', // menu_title
			'manage_options', // capability
			'aws-cognito-graphql', // menu_slug
			array( $this, 'aws_cognito_graphql_create_admin_page' ), // function
			'dashicons-businessman', // icon_url
			2 // position
		);
	}

	public function aws_cognito_graphql_create_admin_page() {
		$this->aws_cognito_graphql_options = get_option( 'aws_cognito_graphql_option_name' ); ?>

		<div class="wrap">
			<h2>AWS Cognito GraphQL</h2>
			<p>Used to access AWS Cognito related properties such as: https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'aws_cognito_graphql_option_group' );
					do_settings_sections( 'aws-cognito-graphql-admin' );
					submit_button();
				?>
			</form>
			<button id="sync_button">Sync JWKS</button>
			<p>Cognito JWKS: <?php
			printf(get_option('cognito_jwks'));
			?></p>
		</div>
		<script type="text/javascript">
		jQuery('#sync_button').click(function(){
		console.log('dfsdfsdf');
            jQuery.ajax({
                type: "POST",
                url: ajaxurl,
                data: { action: 'sync_cognito_jwks' , param: 'st1' }
              }).done(function( msg ) {
                     alert( "Data Saved: " + msg.response );
                     location.reload();
                     return false;
             });
         });
		</script>
	<?php }

	public function aws_cognito_graphql_page_init() {
		register_setting(
			'aws_cognito_graphql_option_group', // option_group
			'aws_cognito_graphql_option_name', // option_name
			array( $this, 'aws_cognito_graphql_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'aws_cognito_graphql_setting_section', // id
			'Settings', // title
			array( $this, 'aws_cognito_graphql_section_info' ), // callback
			'aws-cognito-graphql-admin' // page
		);

		add_settings_field(
			'aws_cognito_region', // id
			'Region', // title
			array( $this, 'aws_cognito_region_callback' ), // callback
			'aws-cognito-graphql-admin', // page
			'aws_cognito_graphql_setting_section' // section
		);

		add_settings_field(
			'aws_cognito_poolid', // id
			'Pool Id', // title
			array( $this, 'aws_cognito_poolid_callback' ), // callback
			'aws-cognito-graphql-admin', // page
			'aws_cognito_graphql_setting_section' // section
		);

	}

	public function aws_cognito_graphql_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['aws_cognito_region'] ) ) {
			$sanitary_values['aws_cognito_region'] = sanitize_text_field( $input['aws_cognito_region'] );
		}

		if ( isset( $input['aws_cognito_poolid'] ) ) {
			$sanitary_values['aws_cognito_poolid'] = sanitize_text_field( $input['aws_cognito_poolid'] );
		}

		return $sanitary_values;
	}

	public function aws_cognito_graphql_section_info() {

	}

	public function aws_cognito_region_callback() {
		printf(
			'<input class="regular-text" type="text" name="aws_cognito_graphql_option_name[aws_cognito_region]" id="aws_cognito_region" value="%s">',
			isset( $this->aws_cognito_graphql_options['aws_cognito_region'] ) ? esc_attr( $this->aws_cognito_graphql_options['aws_cognito_region']) : ''
		);
	}

	public function aws_cognito_poolid_callback() {
		printf(
			'<input class="regular-text" type="text" name="aws_cognito_graphql_option_name[aws_cognito_poolid]" id="aws_cognito_poolid" value="%s">',
			isset( $this->aws_cognito_graphql_options['aws_cognito_poolid'] ) ? esc_attr( $this->aws_cognito_graphql_options['aws_cognito_poolid']) : ''
		);
	}

}



/*
 * Retrieve this value with:
 * $aws_cognito_graphql_options = get_option( 'aws_cognito_graphql_option_name' ); // Array of All Options
 * $aws_cognito_region = $aws_cognito_graphql_options['aws_cognito_region']; // Region
 * $aws_cognito_poolid = $aws_cognito_graphql_options['aws_cognito_poolid']; // Pool Id
 */
